/**
 * Smart Event Open API
 * Smart Event Open API documentation
 *
 * OpenAPI spec version: 2.0.12
 * Contact: info@smartevent.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TranslationCategory from './TranslationCategory';

/**
* The CategoryChild model module.
* @module model/CategoryChild
* @version 2.0.12
*/
export default class CategoryChild {
    /**
    * Constructs a new <code>CategoryChild</code>.
    * @alias module:model/CategoryChild
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>CategoryChild</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/CategoryChild} obj Optional instance to populate.
    * @return {module:model/CategoryChild} The populated <code>CategoryChild</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CategoryChild();
                        
            
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('translations')) {
                obj['translations'] = ApiClient.convertToType(data['translations'], {'String': TranslationCategory});
            }
        }
        return obj;
    }

    /**
    * @member {String} code
    */
    code = undefined;
    /**
    * Keys reference to locale of a translation
    * @member {Object.<String, module:model/TranslationCategory>} translations
    */
    translations = undefined;




}
