/**
 * Smart Event Open API
 * Smart Event Open API documentation
 *
 * OpenAPI spec version: 2.0.9
 * Contact: info@smartevent.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Category from './Category';
import TranslationCategory from './TranslationCategory';

/**
* The Category model module.
* @module model/Category
* @version 2.0.9
*/
export default class Category {
    /**
    * Constructs a new <code>Category</code>.
    * @alias module:model/Category
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Category</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Category} obj Optional instance to populate.
    * @return {module:model/Category} The populated <code>Category</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Category();
                        
            
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('translations')) {
                obj['translations'] = ApiClient.convertToType(data['translations'], {'String': [TranslationCategory]});
            }
            if (data.hasOwnProperty('parent')) {
                obj['parent'] = Category.constructFromObject(data['parent']);
            }
        }
        return obj;
    }

    /**
    * @member {String} code
    */
    code = undefined;
    /**
    * Keys reference to locale of a translation
    * @member {Object.<String, Array.<module:model/TranslationCategory>>} translations
    */
    translations = undefined;
    /**
    * @member {module:model/Category} parent
    */
    parent = undefined;




}
