/**
 * Smart Event Open API
 * Smart Event Open API documentation
 *
 * OpenAPI spec version: 2.0.8
 * Contact: info@smartevent.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BillingData from './BillingData';
import Currency from './Currency';
import Locale from './Locale';

/**
* The Channel model module.
* @module model/Channel
* @version 2.0.8
*/
export default class Channel {
    /**
    * Constructs a new <code>Channel</code>.
    * @alias module:model/Channel
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Channel</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Channel} obj Optional instance to populate.
    * @return {module:model/Channel} The populated <code>Channel</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Channel();
                        
            
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('default_locale')) {
                obj['default_locale'] = ApiClient.convertToType(data['default_locale'], [Locale]);
            }
            if (data.hasOwnProperty('currencies')) {
                obj['currencies'] = ApiClient.convertToType(data['currencies'], [Currency]);
            }
            if (data.hasOwnProperty('contact_email')) {
                obj['contact_email'] = ApiClient.convertToType(data['contact_email'], 'String');
            }
            if (data.hasOwnProperty('billing_data')) {
                obj['billing_data'] = ApiClient.convertToType(data['billing_data'], [BillingData]);
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('hostname')) {
                obj['hostname'] = ApiClient.convertToType(data['hostname'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} code
    */
    code = undefined;
    /**
    * @member {String} name
    */
    name = undefined;
    /**
    * @member {Array.<module:model/Locale>} default_locale
    */
    default_locale = undefined;
    /**
    * @member {Array.<module:model/Currency>} currencies
    */
    currencies = undefined;
    /**
    * @member {String} contact_email
    */
    contact_email = undefined;
    /**
    * @member {Array.<module:model/BillingData>} billing_data
    */
    billing_data = undefined;
    /**
    * @member {String} description
    */
    description = undefined;
    /**
    * @member {String} hostname
    */
    hostname = undefined;




}
