/**
 * Smart Event Open API
 * Smart Event Open API documentation
 *
 * OpenAPI spec version: 2.0.8
 * Contact: info@smartevent.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The ChannelPricing model module.
* @module model/ChannelPricing
* @version 2.0.8
*/
export default class ChannelPricing {
    /**
    * Constructs a new <code>ChannelPricing</code>.
    * @alias module:model/ChannelPricing
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>ChannelPricing</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ChannelPricing} obj Optional instance to populate.
    * @return {module:model/ChannelPricing} The populated <code>ChannelPricing</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ChannelPricing();
                        
            
            if (data.hasOwnProperty('channel_code')) {
                obj['channel_code'] = ApiClient.convertToType(data['channel_code'], 'String');
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'Number');
            }
            if (data.hasOwnProperty('original_price')) {
                obj['original_price'] = ApiClient.convertToType(data['original_price'], 'Number');
            }
            if (data.hasOwnProperty('price_reduced')) {
                obj['price_reduced'] = ApiClient.convertToType(data['price_reduced'], 'Boolean');
            }
        }
        return obj;
    }

    /**
    * @member {String} channel_code
    */
    channel_code = undefined;
    /**
    * @member {Number} price
    */
    price = undefined;
    /**
    * @member {Number} original_price
    */
    original_price = undefined;
    /**
    * @member {Boolean} price_reduced
    */
    price_reduced = undefined;




}
