/**
 * Smart Event Open API
 * Smart Event Open API documentation
 *
 * OpenAPI spec version: 2.0.15
 * Contact: info@smartevent.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ChannelPricing from './ChannelPricing';

/**
* The ChannelPricings model module.
* @module model/ChannelPricings
* @version 2.0.15
*/
export default class ChannelPricings {
    /**
    * Constructs a new <code>ChannelPricings</code>.
    * Keys reference to code of a channel
    * @alias module:model/ChannelPricings
    * @class
    * @extends Object
    */

    constructor() {
        
        
        return this;
    }

    /**
    * Constructs a <code>ChannelPricings</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ChannelPricings} obj Optional instance to populate.
    * @return {module:model/ChannelPricings} The populated <code>ChannelPricings</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ChannelPricings();
            ApiClient.constructFromObject(data, obj, 'ChannelPricing');
            
            
        }
        return obj;
    }





}
