/**
 * Smart Event Open API
 * Smart Event Open API documentation
 *
 * OpenAPI spec version: 2.0.7
 * Contact: info@smartevent.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The NotDescribed model module.
* @module model/NotDescribed
* @version 2.0.7
*/
export default class NotDescribed {
    /**
    * Constructs a new <code>NotDescribed</code>.
    * @alias module:model/NotDescribed
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>NotDescribed</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/NotDescribed} obj Optional instance to populate.
    * @return {module:model/NotDescribed} The populated <code>NotDescribed</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NotDescribed();
                        
            
        }
        return obj;
    }





}
