/**
 * Smart Event Open API
 * Smart Event Open API documentation
 *
 * OpenAPI spec version: 2.0.15
 * Contact: info@smartevent.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Channel from './Channel';
import OrderItem from './OrderItem';

/**
* The Order model module.
* @module model/Order
* @version 2.0.15
*/
export default class Order {
    /**
    * Constructs a new <code>Order</code>.
    * @alias module:model/Order
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Order</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Order} obj Optional instance to populate.
    * @return {module:model/Order} The populated <code>Order</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Order();
                        
            
            if (data.hasOwnProperty('token_value')) {
                obj['token_value'] = ApiClient.convertToType(data['token_value'], 'String');
            }
            if (data.hasOwnProperty('channel')) {
                obj['channel'] = ApiClient.convertToType(data['channel'], [Channel]);
            }
            if (data.hasOwnProperty('checkout_state')) {
                obj['checkout_state'] = ApiClient.convertToType(data['checkout_state'], 'String');
            }
            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], [OrderItem]);
            }
            if (data.hasOwnProperty('referer')) {
                obj['referer'] = ApiClient.convertToType(data['referer'], 'String');
            }
            if (data.hasOwnProperty('google_analytics_code')) {
                obj['google_analytics_code'] = ApiClient.convertToType(data['google_analytics_code'], 'String');
            }
            if (data.hasOwnProperty('invoice_exception')) {
                obj['invoice_exception'] = ApiClient.convertToType(data['invoice_exception'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} token_value
    */
    token_value = undefined;
    /**
    * @member {Array.<module:model/Channel>} channel
    */
    channel = undefined;
    /**
    * @member {String} checkout_state
    */
    checkout_state = undefined;
    /**
    * @member {Array.<module:model/OrderItem>} items
    */
    items = undefined;
    /**
    * Id of affiliate referer
    * @member {String} referer
    */
    referer = undefined;
    /**
    * Google Analytics conversion code used to send GA notification after payment
    * @member {String} google_analytics_code
    */
    google_analytics_code = undefined;
    /**
    * Information why invoice can not be issued
    * @member {String} invoice_exception
    */
    invoice_exception = undefined;




}
