/**
 * Smart Event Open API
 * Smart Event Open API documentation
 *
 * OpenAPI spec version: 2.0.8
 * Contact: info@smartevent.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The TaxCategory model module.
* @module model/TaxCategory
* @version 2.0.8
*/
export default class TaxCategory {
    /**
    * Constructs a new <code>TaxCategory</code>.
    * @alias module:model/TaxCategory
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>TaxCategory</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/TaxCategory} obj Optional instance to populate.
    * @return {module:model/TaxCategory} The populated <code>TaxCategory</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TaxCategory();
                        
            
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} code
    */
    code = undefined;
    /**
    * @member {String} name
    */
    name = undefined;
    /**
    * @member {String} description
    */
    description = undefined;




}
