/**
 * Smart Event Open API
 * Smart Event Open API documentation
 *
 * OpenAPI spec version: 2.0.15
 * Contact: info@smartevent.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SmartEventOpenApi);
  }
}(this, function(expect, SmartEventOpenApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SmartEventOpenApi.CalculateResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CalculateResponse', function() {
    it('should create an instance of CalculateResponse', function() {
      // uncomment below and update the code to test CalculateResponse
      //var instane = new SmartEventOpenApi.CalculateResponse();
      //expect(instance).to.be.a(SmartEventOpenApi.CalculateResponse);
    });

    it('should have the property total (base name: "total")', function() {
      // uncomment below and update the code to test the property total
      //var instane = new SmartEventOpenApi.CalculateResponse();
      //expect(instance).to.be();
    });

    it('should have the property promotions (base name: "promotions")', function() {
      // uncomment below and update the code to test the property promotions
      //var instane = new SmartEventOpenApi.CalculateResponse();
      //expect(instance).to.be();
    });

    it('should have the property channel (base name: "channel")', function() {
      // uncomment below and update the code to test the property channel
      //var instane = new SmartEventOpenApi.CalculateResponse();
      //expect(instance).to.be();
    });

    it('should have the property currency (base name: "currency")', function() {
      // uncomment below and update the code to test the property currency
      //var instane = new SmartEventOpenApi.CalculateResponse();
      //expect(instance).to.be();
    });

    it('should have the property locale (base name: "locale")', function() {
      // uncomment below and update the code to test the property locale
      //var instane = new SmartEventOpenApi.CalculateResponse();
      //expect(instance).to.be();
    });

    it('should have the property checkId (base name: "check_id")', function() {
      // uncomment below and update the code to test the property checkId
      //var instane = new SmartEventOpenApi.CalculateResponse();
      //expect(instance).to.be();
    });

  });

}));
