/**
 * Smart Event Open API
 * Smart Event Open API documentation
 *
 * OpenAPI spec version: 2.0.7
 * Contact: info@smartevent.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SmartEventOpenApi);
  }
}(this, function(expect, SmartEventOpenApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SmartEventOpenApi.Channel();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Channel', function() {
    it('should create an instance of Channel', function() {
      // uncomment below and update the code to test Channel
      //var instane = new SmartEventOpenApi.Channel();
      //expect(instance).to.be.a(SmartEventOpenApi.Channel);
    });

    it('should have the property code (base name: "code")', function() {
      // uncomment below and update the code to test the property code
      //var instane = new SmartEventOpenApi.Channel();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new SmartEventOpenApi.Channel();
      //expect(instance).to.be();
    });

    it('should have the property defaultLocale (base name: "default_locale")', function() {
      // uncomment below and update the code to test the property defaultLocale
      //var instane = new SmartEventOpenApi.Channel();
      //expect(instance).to.be();
    });

    it('should have the property currencies (base name: "currencies")', function() {
      // uncomment below and update the code to test the property currencies
      //var instane = new SmartEventOpenApi.Channel();
      //expect(instance).to.be();
    });

    it('should have the property contactEmail (base name: "contact_email")', function() {
      // uncomment below and update the code to test the property contactEmail
      //var instane = new SmartEventOpenApi.Channel();
      //expect(instance).to.be();
    });

    it('should have the property billingData (base name: "billing_data")', function() {
      // uncomment below and update the code to test the property billingData
      //var instane = new SmartEventOpenApi.Channel();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new SmartEventOpenApi.Channel();
      //expect(instance).to.be();
    });

    it('should have the property hostname (base name: "hostname")', function() {
      // uncomment below and update the code to test the property hostname
      //var instane = new SmartEventOpenApi.Channel();
      //expect(instance).to.be();
    });

  });

}));
