/**
 * Smart Event Open API
 * Smart Event Open API documentation
 *
 * OpenAPI spec version: 2.0.9
 * Contact: info@smartevent.pl
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SmartEventOpenApi);
  }
}(this, function(expect, SmartEventOpenApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SmartEventOpenApi.ChannelPricing();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ChannelPricing', function() {
    it('should create an instance of ChannelPricing', function() {
      // uncomment below and update the code to test ChannelPricing
      //var instane = new SmartEventOpenApi.ChannelPricing();
      //expect(instance).to.be.a(SmartEventOpenApi.ChannelPricing);
    });

    it('should have the property channelCode (base name: "channel_code")', function() {
      // uncomment below and update the code to test the property channelCode
      //var instane = new SmartEventOpenApi.ChannelPricing();
      //expect(instance).to.be();
    });

    it('should have the property price (base name: "price")', function() {
      // uncomment below and update the code to test the property price
      //var instane = new SmartEventOpenApi.ChannelPricing();
      //expect(instance).to.be();
    });

    it('should have the property originalPrice (base name: "original_price")', function() {
      // uncomment below and update the code to test the property originalPrice
      //var instane = new SmartEventOpenApi.ChannelPricing();
      //expect(instance).to.be();
    });

    it('should have the property priceReduced (base name: "price_reduced")', function() {
      // uncomment below and update the code to test the property priceReduced
      //var instane = new SmartEventOpenApi.ChannelPricing();
      //expect(instance).to.be();
    });

  });

}));
